name: 'All tests'
on: 
  push:
    branches:
      - HW1

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Valgrind
      run: sudo apt-get install -y valgrind
    - name: Install GoogleTests
      run: sudo apt-get install -y googletest && sudo apt-get install libgtest-dev
    - name: Install CppCheck
      run: sudo apt-get install -y cppcheck
    - name: Run Linter
      run: cd hw1/src && cppcheck *.c
    - name: Make
      run: cd hw1/cmake-build-debug && cmake .. && make
    - name: Test
      run: cd hw1/cmake-build-debug && make ./tests && ./tests
    - name: Valgrind
      run: valgrind --tool=memcheck --leak-check=yes hw1/src/main.c
