name: CMake

on: [pull_request, push]

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Valgrind
      run: sudo apt-get install -y valgrind
    - name: Install GoogleTests
      run: sudo apt-get install -y googletest && sudo apt-get install libgtest-dev
    - name: Install СppСheck
      run: sudo apt-get install -y cppcheck
    - name: Run Linter
      run: cd hw1/src && cppcheck *.c
    - name: Configure
      run: sh configure.sh
    - name: Make
      run: cd hw1/build && cmake .. && make
    - name: Tests
      run: cd hw1/build && make ./tests && ./tests
